version: '3'
services:
  web:
      build: .
      ports:
          - "1433:1433"
      depends_on:
          - db
  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379"
  #   networks:
  #     - frontend
  #   deploy:
  #     replicas: 2
  #     update_config:
  #       parallelism: 2
  #       delay: 10s
  #     restart_policy:
  #       condition: on-failure
